---
title: "Extract MS2 Pure Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Extract MS2 Pure Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
   warning = FALSE
)
```

```{r setup}
library(DIANMF)
```

## Load raw MSnbase data of a mzML file
```{r load mzML file and read its MSnbase raw data, echo=TRUE }
file <- "C:/Users/DK273056/Documents/1workflow/DIA_NMF_workflow/mzML/20170803_FS-DIA-E2-10ng-rep3_pos_51.mzML"
rawData.onDiskMSnExp <- MSnbase::readMSData(file, mode = "onDisk")
rawData.onDiskMSnExp
```

## Detect MS1 peaks using XCMS
```{r detect MS1 peaks using xcms, echo=TRUE, message=FALSE, warning=FALSE}
eics_peaks <- detect_peaks_by_xcms(rawData.onDiskMSnExp = rawData.onDiskMSnExp,
                                     ppm = 7, peakwidth = c(6,60), snthresh = 1,
                                     prefilter = c(5,4000), mzCenterFun = "wMeanApex3",
                                     integrate = 2, mzdiff = -0.001, noise = 0,
                                     firstBaselineCheck = FALSE )
  
eics_peaks.mat <- xcms::chromPeaks(eics_peaks)
ms1_peaks.df <- prepare_ms1_peaks(ms1_peaks = eics_peaks.mat) # prepare the peaks
```

## Choose a MS1 peak to identify it
```{r choose MS1 peak, echo=TRUE }
peak.idx <- 1 
mz_prec <- ms1_peaks.df[peak.idx, 'mz']
rt_prec <- ms1_peaks.df[peak.idx, 'rt']
```

## Extract MS1 and MS2 pure information
```{r main fct for MS1 spectrum, echo=TRUE }
all_info_peak1 <- dia.nmf.f( mzML_path = file,
                          MS_level = "MS2", ppm = 7,
                          ms1_peaks = eics_peaks.mat,
                          peaks_nb = 1,
                          rt_index = TRUE, 
                          maximumIteration = 10, maxFBIteration = 10, toleranceFB = 1e-5,
                          MS1_init_method = 'nndsvd', errors_print = FALSE,
                          rt_tol = 2)

ms1_pure_spectrum <- all_info_peak1[[1]]$MS1_pure_spectrum
print(ms1_pure_spectrum)

ms2_pure_spectrum <- all_info_peak1[[1]]$MS2_pure_spectrum_specific
print(ms2_pure_spectrum)
```