---
title: "Extract Pure MS1 Spectra"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Extract Pure MS1 Spectra}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  comment = "#>"
)
```

```{r setup}
library(DIANMF)
```

This vignette aims to:

### Load mzML file
```{r load compounds table, echo=TRUE}
data_example
```

The example dataset is an `r class(data_example)`.

### Detect MS1 peaks in this mzML file using XCMS
```{r detect MS1 peaks, echo=TRUE}
eics_rawData <- detect_EICs.f(
    rawData.onDiskMSnExp = data_example,
    d.out = NULL,
    ppm = 6,
    peakwidth = c(3,60),
    snthresh = 0,
    prefilter = c(5,4000),
    mzCenterFun = "wMeanApex3",
    integrate = 2,
    mzdiff = -0.001,
    noise = 0,
    firstBaselineCheck = FALSE
  )

eics_peaks.mat <- xcms::chromPeaks(eics_rawData)
eics_peaks.mat <- as.matrix(eics_peaks.mat[order(-eics_peaks.mat[, 'into']), ])
ms1_peaks.df <- as.data.frame(eics_peaks.mat)

head(ms1_peaks.df)
print(paste0(nrow(ms1_peaks.df), " peaks were found."))
```

### Extract the MS1 pure spectrum of peaks 2 which is related to Aminophenol one of the spiked compound
```{r extract the MS1 peak, echo=TRUE}
peak.idx <- 2
amino_peak <- ms1_peaks.df[peak.idx, ]
amino_peak
mz_prec <- ms1_peaks.df[peak.idx, 'mz']
rt_prec <- ms1_peaks.df[peak.idx, 'rt']
```

```{r extract the MS1 mixed data, echo=TRUE}
ms1_mat <- extract_ms_matrix.f(idx.pg = peak.idx, eics_peaks.mat = ms1_peaks.df,
                                 rawData.onDiskMSnExp = data_example,
                                 ppm = 7, rt_index = TRUE, mz_range = NULL, iso_win_index = NULL)
row_filter <- apply(ms1_mat, 1, has_four_consecutive_non_zero)
ms1_mat <- ms1_mat[row_filter, , drop = FALSE]
head(ms1_mat)
```

```{r prepare the mixed data, echo=TRUE}
mixed_ms1_data <- prepare_mixed_data(m = ms1_mat, mz_value = as.numeric(rownames(ms1_mat)), rt = as.numeric(colnames(ms1_mat)) )
```

```{r factorize the MS1 mixed data, echo=TRUE}
ngmcas_res <- nGMCAs(originalMatrix = ms1_mat, rank = 3,
                       maximumIteration = 10, maxFBIteration = 5, toleranceFB = 1e-5,
                       initialization_method = "nndsvd",
                       errors_print = FALSE)
W_ms1 <- ngmcas_res$S
H_ms1 <- ngmcas_res$A
```

```{r plot the raw and pure elution profiles, echo=TRUE}
p <- plot_MS_eics(ms_mixed = ms1_mat, ms_pure_H = H_ms1, ms_level = "MS1", rt_prec = rt_prec, choosen_comp = 2) 
p
```

```{r plot the raw and pure spectra, echo=TRUE, results = "asis"}
plot_MS_spectra(ms_mixed = ms1_mat, ms_pure_W = W_ms1, ms_level = "MS1", mz_prec = mz_prec, choosen_comp = 2)
```

```{r extract the corresponding MS1 pure spectra, echo=TRUE, results = "asis"}
mz_ms1_ions <- round(as.numeric(rownames(W_ms1)), 4)
ms1_pure_spectra <- prepare_pure_spectra(W_ms1)

closest_row <- which.min(abs(mz_ms1_ions - mz_prec))
choosen_comp_ms1 <- which.max(W_ms1[closest_row, ])
ms1_pure_spectrum <- ms1_pure_spectra[ms1_pure_spectra$comp_nb == paste0('comp',choosen_comp_ms1), ]
ms1_pure_spectrum <- ms1_pure_spectrum[, c('mz_value', 'intensity')]
ms1_pure_spectrum <- ms1_pure_spectrum[ms1_pure_spectrum['intensity'] != 0, ]
```

### start processing MS2 data
```{r extract the MS2 mixed data step1, echo=TRUE}
min_mz <- min(ms1_pure_spectrum$mz_value)
max_mz <- max(ms1_pure_spectrum$mz_value)
info.swath <- isolationWindows.range(data_example)
# idx.swath <- which(info.swath$lowerMz %between% c(min_mz, max_mz) | info.swath$upperMz %between% c(min_mz, max_mz))
```

```{r extract the MS2 mixed data step2, echo=TRUE}

```
